services:
  # -------------------- FRONTEND --------------------
  frontend:
    image: nginx:latest
    container_name: jardin_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - api

  # -------------------- API --------------------
  api:
    build: ./api
    container_name: jardin_api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo-primary:27017/jardin
    depends_on:
      mongo-primary:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep java || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # -------------------- MONGO PRIMARY --------------------
  mongo-primary:
    image: mongo:7.0
    container_name: jardin_mongo_primary
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-primary-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -------------------- MONGO REPLICA --------------------
  mongo-replica:
    image: mongo:7.0
    container_name: jardin_mongo_replica
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-replica-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

# -------------------- VOLUMENES --------------------
volumes:
  mongo-primary-data:
  mongo-replica-data: